version: '3'

services:
  expressjs:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "5320:5000"
    volumes:
      - /data/callcaptcha-service/node_modules:/home/node/app/node_modules
